# Generated by Django 3.2 on 2023-09-24 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=10, message='Не более 10 баллов.'), django.core.validators.MinValueValidator(limit_value=1, message='Не менее 1 балла.')], verbose_name='Рейтинг'),
        ),
    ]
