# Generated by Django 3.2 on 2023-09-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
